### ISSUE TITLE
i made your website look a little bit better

### ISSUE THREAD

**Issue by ghost** [moom0o/moobotsite#1]
take a look! https://www.mediafire.com/file/800jvq2wc4gfn9i/style.css/file https://www.mediafire.com/file/q8hxo9hpegrg29k/README.md/file https://www.mediafire.com/file/g65uihkqmilr62i/LICENSE/file https://www.mediafire.com/file/g65uihkqmilr62i/LICENSE/file https://www.mediafire.com/file/rxg3rfhplxfn7gs/index.html/file https://www.mediafire.com/file/gtbyr3bnwwemrs5/content.json/file 
https://www.mediafire.com/file/qrpoevhqwtlop2o/CNAME/file

**Comment by moom0o** [comment]
Please make a pull request

**Comment by ghost** [comment]
ok
